# Default values for papertrail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gliderlabs/logspout
  tag: master
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 0.15
  limits:
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
