# Default values for travis-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay:io/travisci/travis-api
  tag: ''
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

nameOverride: ""
fullnameOverride: ""

resources:
 limits:
  cpu: 500m
  memory: 512Mi
 requests:
  cpu: 100m
  memory: 128Mi

autoscaling:
  enabled: "true"
  minReplicas: 2
  maxReplicas: 6
  targetAverageCPUUtilization: 75
  targetAverageMemoryValue: 2000Mi

nodeSelector: {}

tolerations: []

affinity: {}

vault:
  secret: travis-api-staging-org
