apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "macstadium-worker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "macstadium-worker.name" . }}
    helm.sh/chart: {{ include "macstadium-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: macstadium-workers
  env: {{ .Values.secretEnv }}
  prefix: TRAVIS_WORKER
  pro: {{ eq .Values.site "com" }}
