---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: gce-staging-services-1
  labels:
    chart: contour
spec:
  releaseName: contour
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: contour
    version: 0.2.0
  values:
    hpa:
      create: "true"
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 85
    service:
      externalTrafficPolicy: "Local"
