---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: gce-staging-services-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  rollback:
    enable: true
    force: true
    timeout: 300
    wait: false
