---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: gce-staging-services-1
  labels:
    chart: reloader
spec:
  releaseName: reloader
  chart:
    repository: https://hub.helm.sh/charts/stable/reloader
    name: stable/reloader
    version: 1.2.0
  values:
    replicaCount: 1
