apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-sandbox
spec:
  selector:
    matchLabels:
      app: secrets-sandbox
  replicas: 1 
  template:
    metadata:
      labels:
        app: secrets-sandbox
    spec:
      containers:
      - name: alpine
        image: alpine
