apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-sandbox
  namespace: gce-staging-services-1
spec:
  selector:
    matchLabels:
      app: secrets-sandbox
  replicas: 1 
  template:
    metadata:
      labels:
        app: secrets-sandbox
    spec:
      containers:
      - name: nginx
        image: nginx
