---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault-staging
  namespace: gce-staging-services-1
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    path: "."
    git: git@github.com:r-arek/vault-helm.git
    ref: master
  releaseName: vault-staging
  values:
    replicaCount: 1
    ingress:
      enabled: false
