apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "papertrail.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "papertrail.name" . }}
    helm.sh/chart: {{ include "papertrail.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "papertrail.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "papertrail.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: log
          hostPath:
              path: /var/run/docker.sock
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SYSLOG_TAG
              value: '{{ "{{" }} index .Container.Config.Labels "io.kubernetes.pod.namespace" {{ "}}" }}[{{ "{{" }} index .Container.Config.Labels "io.kubernetes.pod.name" {{ "}}" }}]'
            - name: SYSLOG_HOSTNAME
              value: '{{ "{{" }} index .Container.Config.Labels "io.kubernetes.container.name" {{ "}}" }}'
            - name: ROUTE_URIS
              value: {{ .Values.endpoint }}
          volumeMounts:
            - name: log
              mountPath: /var/run/docker.sock
          resources:
{{ toYaml .Values.resources | indent 12 }}
