apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: worker-org
  namespace: macstadium-prod-1
  labels:
    chart: macstadium-worker
spec:
  chartGitPath: macstadium-worker
  releaseName: worker-org
  values:
    # Eventually this should be:
    # replicaCount: 8
    replicaCount: 1
    site: org
    poolSize: 20
    jupiterBrainName: jupiter-brain-org
    secretEnv: production-common
