apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: worker-com
  namespace: macstadium-prod-1
  labels:
    chart: macstadium-worker
spec:
  chartGitPath: macstadium-worker
  releaseName: worker-com
  values:
    image:
      tag: v4.6.3
    # Eventually this should be:
    # replicaCount: 5
    replicaCount: 1
    site: com
    poolSize: 21
    jupiterBrainName: jupiter-brain-com
    secretEnv: production-common
