apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{ include "n8n.labels" . | indent 4 | trim }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{ include "n8n.selector" . | indent 6 | trim }}
  template:
    metadata:
      labels:
        {{ include "n8n.selector" . | indent 8 | trim }}
    spec:
      containers:
        - name: {{ include "n8n.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
        {{- with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
        {{- end }}
