apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{ include "n8n.labels" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 5678
      protocol: TCP
  selector:
    {{ include "n8n.selector" . | indent 4 | trim }}
    