apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "vsphere-monitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vsphere-monitor.name" . }}
    helm.sh/chart: {{ include "vsphere-monitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: vsphere-monitor
  env: {{ .Values.secretEnv }}
  prefix: VSPHERE_MONITOR
