apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "macbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "macbot.name" . }}
    helm.sh/chart: {{ include "macbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: macstadium-image-builder
  env: macbot
