apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "imaged.fullname" . }}-ansible
  labels:
    app.kubernetes.io/name: imaged-ansible
    helm.sh/chart: {{ include "macbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: macstadium-image-builder
  env: ansible-secrets
  key: ansible.yml
