dependencies:
- name: macstadium-worker
  version: "0.1.0"
  repository: "file://../charts/macstadium-worker"
  alias: worker-org
- name: macstadium-worker
  version: "0.1.0"
  repository: "file://../charts/macstadium-worker"
  alias: worker-com
- name: jupiter-brain
  version: "0.1.0"
  repository: "file://../charts/jupiter-brain"
  alias: jupiter-brain-org
- name: jupiter-brain
  version: "0.1.0"
  repository: "file://../charts/jupiter-brain"
  alias: jupiter-brain-com
- name: vsphere-monitor
  version: "0.1.0"
  repository: "file://../charts/vsphere-monitor"
- name: vsphere-janitor
  version: "0.1.0"
  repository: "file://../charts/vsphere-janitor"
