---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: gce-production-1

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-admin
  namespace: gce-production-1
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-admin-rolebinding
  namespace: gce-production-1
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: gce-production-1
roleRef:
  kind: Role
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: gce-production-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: gce-production-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-kubernetes-synchronizer
  namespace: gce-production-1
  labels:
    appl: vault-kubernetes-synchronizer
spec:
  replicas: 1
  selector:
    matchLabels:
      appl: vault-kubernetes-synchronizer
  template:
    metadata:
      labels:
        appl: vault-kubernetes-synchronizer
    spec:
      serviceAccountName: vault-auth
      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: vault-kubernetes-authenticator
        image: postfinance/vault-kubernetes-authenticator:0.1.4
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: VAULT_ADDR
          value: http://vault.gce-production-1.svc.cluster.local:8200
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_AUTH_MOUNT_PATH
          value: kubernetes
        - name: VAULT_ROLE
          value: vault-auth
        - name: VAULT_TOKEN_PATH
          value: /home/vault/.vault-token
        - name: ALLOW_FAIL
          value: "true"
      containers:
      - name: vault-kubernetes-synchronizer
        image: gcr.io/travis-staging-1/vault-kubernetes-synchronizer:0.1.4-1-loop
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: VAULT_ADDR
          value: http://vault.gce-production-1.svc.cluster.local:8200
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_TOKEN_PATH
          value: /home/vault/.vault-token
        - name: VAULT_SECRETS
          value:  secret/
      - name: vault-kubernetes-token-renewer
        image: postfinance/vault-kubernetes-token-renewer:0.1.4
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: VAULT_ADDR
          value: http://vault.gce-production-1.svc.cluster.local:8200
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_AUTH_MOUNT_PATH
          value: kubernetes
        - name: VAULT_TOKEN_PATH
          value: /home/vault/.vault-token

