apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "vsphere-janitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vsphere-janitor.name" . }}
    helm.sh/chart: {{ include "vsphere-janitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: vsphere-janitor
  env: {{ .Values.secretEnv }}
  prefix: VSPHERE_JANITOR
  pro: true
