# Default values for jupiter-brain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: travisci/jupiter-brain
  tag: v1.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secretEnv: ""
pro: false

concurrency:
  create: 20
  delete: 20

requestTimeout: 5m

honeycomb:
  dataset: ""
  sampleRate: 1

service:
  type: ClusterIP
  port: 80
