apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupiter-brain.fullname" . }}
data:
  JUPITER_BRAIN_VSPHERE_CONCURRENT_CREATE_OPERATIONS: "{{ .Values.concurrency.create }}"
  JUPITER_BRAIN_VSPHERE_CONCURRENT_DELETE_OPERATIONS: "{{ .Values.concurrency.delete }}"
  JUPITER_BRAIN_REQUEST_TIMEOUT: {{ .Values.requestTimeout }}
  JUPITER_BRAIN_HONEYCOMB_REQUEST_DATASET: {{ .Values.honeycomb.dataset }}
  JUPITER_BRAIN_HONEYCOMB_SAMPLE_RATE: "{{ .Values.honeycomb.sampleRate }}"
