apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "jupiter-brain.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jupiter-brain.name" . }}
    helm.sh/chart: {{ include "jupiter-brain.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: jupiter-brain
  env: {{ .Values.secretEnv }}
  prefix: JUPITER_BRAIN
  pro: {{ .Values.pro }}
