apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "statsd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "statsd.name" . }}
    helm.sh/chart: {{ include "statsd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  app: terraform-config
  env: {{ .Values.secretEnv }}
