apiVersion: v1
kind: Service
metadata:
  name: {{ include "statsd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "statsd.name" . }}
    helm.sh/chart: {{ include "statsd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8125
      protocol: UDP
      name: statsd
  selector:
    app.kubernetes.io/name: {{ include "statsd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
