{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "travis-gatekeeper.serviceAccountName" . }}
  labels:
{{ include "travis-gatekeeper.labels" . | nindent 4 }}
{{- end -}}
