# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: 
  repository: n8nio/n8n
  tag: 0.39.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: contour
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    contour.heptio.com/tls-minimum-protocol-version: "1.2"
  hosts:
  - host: n8n.staging.travis-ci.org
    paths: ["/"]
    backend:
      serviceName: n8n
      servicePort: 5678
  tls:
  - secretName: n8n-staging-travis-ci-org-tls
    hosts:
    - n8n.staging.travis-ci.org

resources: 
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
