# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: 
  repository: n8nio/n8n
  tag: 0.39.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: contour
  hosts:
    - host: n8n.staging.travis-ci.org
      paths: ["/"]

resources: 
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
