apiVersion: travisci.com/v1
kind: TrvsSecret
metadata:
  name: {{ include "jupiter-brain.fullname" . }}
spec:
  app: jupiter-brain
  env: {{ .Values.secretEnv }}
  prefix: JUPITER_BRAIN
  pro: {{ .Values.pro }}
