dependencies:
- name: macstadium-worker
  version: "0.1.0"
  repository: "file://../charts/macstadium-worker"
  alias: worker-org
- name: macstadium-jupiter-brain
  version: "0.1.0"
  repository: "file://../charts/macstadium-jupiter-brain"
  alias: jupiter-brain-org
- name: macstadium-jupiter-brain
  version: "0.1.0"
  repository: "file://../charts/macstadium-jupiter-brain"
  alias: jupiter-brain-com
