apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: worker-org
  namespace: gce-staging-1
spec:
  chart:
    path: charts/gce-worker
    git: git@github.com:travis-ci/kubernetes-config.git
    ref: staging
  releaseName: worker-org
  values:
    image:
      tag: v6.2.0

    # 2400 CPUs / 2 vCPU per job = 1200 maxJobs
    cluster:
      enabled: true
      maxJobs: 1000
      maxJobsPerWorker: 50

    site: org

    trvs:
      enabled: true
      app: gce-workers
      env: staging-1
      pro: false
